### ISSUE TITLE
Sometimes getting refresh token issue

### ISSUE THREAD

**Issue by vikram0460** [jonathanraftery/bullhorn-rest-client#1] opened 2018-08-10 06:34 UTC
Sometimes the session refresh is not working.

Is there anyway that we can all the records of candidates, companies, contacts, job orders, placements?

**Comment by jonathanraftery** [comment] 2018-08-10 14:50
Please post specifics of the behavior you're seeing regarding the session refresh. Note that the default memory store used by the auth client depends on write access to the execution directory, and does not offer sufficient security for many environments.

Job orders can be retrieved with
`$client->JobOrders->search($luceneConditions).`
Using conditions such as 'isDeteted:false' will return all active job orders, even if the entity count is greater than the Bullhorn limit of 500 per request. The client will make multiple requests and return the concatenated array of job orders.

Currently, this client offers fairly limited functionality and does not support candidates, placements, etc. Retrieving them is very similar to retrieving the job orders, and the JobOrders class can be used as a guide in pulling the rest. (Eventually we plan to add this to the client by default.)

**Comment by vikram0460** [comment] 2018-08-13 04:48
Thanks for the reply, as it was getting only few times, I missed to capture the screenshot. When I found the  issue arise next time I will have the screenshot and post it here.

By the way thanks for the plug-in it was very useful for me.

**Comment by jonathanraftery** [comment] 2018-08-15 14:32
Thank you! Very glad it was helpful.

I've added the job order entity requests to the readme, and will certainly correct any issues you identify with the session refresh!

**Comment by vikram0460** [comment] 2018-08-22 04:52
Thanks for the update.

There is another issue, it is reoccurring, I think this problem with Bullhorn not with your plug-in. 

Anyway I am posting here it might give you an idea 

I have masked code with XXXXXX original request has different value.

Client error: `GET https://rest31.bullhornstaffing.com/rest-services/XXXXXX/search/Candidate?fields=*&query=isDeleted:0&count=500&start=1000` resulted in a `400 Bad Request` response: { "errorMessage" : "Could not access HTTP invoker remote service at [http://sl131dataservices.vip.bos.bullhorn.com/dat (truncated...) /var/www/html/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php113

**Comment by jonathanraftery** [comment] 2018-09-10 08:59
This is most often caused by incorrect credentials (clientID or client secret). However, it will also occur with credentials which have never been used before, as the client will run into the terms of service acknowledgement, which it currently does not automate through. In that case, you will need to manually go through the OAuth login one time, using those credentials, to clear the ToS acknowledgement.

**Comment by jonathanraftery** [comment] 2018-09-14 14:59
Regarding the refresh issues, see issue #4 . This is quite likely the cause of the problems you were experiencing (now fixed).

**Closed** 2018-09-23 18:48 UTC

**Comment by vikram0460** [comment] 2018-10-04 10:50
Issue is re occurring.
